//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PraktikaVolkov
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moving
    {
        public int IdMoving { get; set; }
        public System.DateTime DateMoving { get; set; }
        public int IdEmployee { get; set; }
        public int IdPost { get; set; }
        public int FromDepartment { get; set; }
        public int InDepartment { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Post Post { get; set; }
    }
}
